name: nutrilens
description: 'NutriLens: Your Personal Nutrition Assistant'
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.5
  permission_handler: ^11.0.1
  speech_to_text: ^7.3.0
  get_it: ^9.1.1
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.0.2
  intl: ^0.19.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: '^0.14.4'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
